default: &default
  adapter:  "mysql2"

  host:     <%= ENV['VELUM_DB_HOST'] || "" %>
  port:     <%= ENV['VELUM_DB_PORT'] || 0 %>
  username: <%= ENV['VELUM_DB_USERNAME'] || "root" %>
  password: <%= ENV['VELUM_DB_PASSWORD'] || "" %>
  encoding: utf8
  pool:     <%= ENV['VELUM_DB_POOL'] || 5 %>
<% if ENV['VELUM_DB_SOCKET'] %>
  socket:   <%= ENV['VELUM_DB_SOCKET'] %>
<% end %>

<%= Rails.env.downcase %>:
  <<: *default
  database: <%= Rails.env.downcase == 'test' ? 'velum_test' : (ENV['VELUM_DB_NAME'] || "velum_#{Rails.env.downcase}") %>
